export const capabilities = [
  "prompt-to-parametric-model",
  "reference-benchmarking",
  "project-versioning",
  "multi-agent-swarm-control",
  "agent-task-orchestration",
  "scenario-simulation",
  "materials-and-cost-tracking",
  "geometry-validation",
  "cad-kernel-validation",
  "qa-release-gates",
  "global-model-marketplace",
  "localized-listing-metadata",
  "license-and-rights-compliance",
  "cad-repair-recommendations",
  "real-estate-massing-generation",
  "prompt-to-real-estate-model",
  "image-to-floor-plan-extraction",
  "photo-to-facade-and-style",
  "video-to-3d-reconstruction",
  "drone-footage-to-site-model",
  "multimodal-brief-intake",
  "floor-plan-to-3d-building",
  "bim-ifc-property-sets",
  "zoning-and-setback-checks",
  "interior-staging-generation",
  "virtual-tour-export",
  "property-listing-sales-pack",
  "immersive-workbench-ui",
  "export-pipeline-ready",
] as const;

export type Capability = (typeof capabilities)[number];
