import type { ParametricFeature } from "./spec.js";

export const parametricLibrary: Record<string, ParametricFeature> = {
  plate: {
    name: "plate",
    description: "Simple parametric plate with configurable dimensions and thickness.",
    values: {
      width: 120,
      height: 80,
      thickness: 8,
    },
  },
  bracket: {
    name: "bracket",
    description: "Structural bracket with flange and hole options.",
    values: {
      width: 140,
      height: 90,
      thickness: 10,
      holes: 4,
    },
  },
  enclosure: {
    name: "enclosure",
    description: "Simple box enclosure for product packaging or small devices.",
    values: {
      width: 180,
      depth: 120,
      height: 70,
      wall: 3,
    },
  },
  "residential-building": {
    name: "residential-building",
    description: "Residential construction massing with site, floors, rooms, parking, facade and tour-ready zones.",
    values: {
      lotWidthM: 12,
      lotDepthM: 30,
      builtAreaM2: 180,
      floors: 1,
      bedrooms: 3,
      parkingSpots: 2,
      livingIntegration: true,
      export: "GLB + IFC + render pack",
    },
  },
  "commercial-building": {
    name: "commercial-building",
    description: "Commercial shell with storefront, leasable area, service zones, circulation and fit-out presets.",
    values: {
      frontageM: 18,
      depthM: 42,
      leasableAreaM2: 620,
      floors: 2,
      storefronts: 4,
      parkingSpots: 18,
      export: "GLB + leasing views + IFC",
    },
  },
  "multi-family-building": {
    name: "multi-family-building",
    description: "Apartment tower feasibility model with levels, unit mix, core, parking and area schedule.",
    values: {
      lotAreaM2: 2400,
      floors: 18,
      unitsPerFloor: 6,
      averageUnitM2: 68,
      parkingRatio: 1.2,
      export: "IFC + GLB + investor pack",
    },
  },
  "industrial-warehouse": {
    name: "industrial-warehouse",
    description: "Light-industrial warehouse with clear-span structure, loading bays, office pod and yard layout.",
    values: {
      frontageM: 24,
      depthM: 48,
      floorAreaM2: 1150,
      clearHeightM: 10,
      loadingBays: 4,
      officePods: 2,
      parkingSpots: 12,
      dockLeveler: true,
      export: "GLB + IFC + layout PDF",
    },
  },
  "office-tower": {
    name: "office-tower",
    description: "Corporate office tower with rentable floors, lobby, mechanical core, elevator bank and parking basement.",
    values: {
      frontageM: 22,
      depthM: 30,
      leasableAreaM2: 900,
      floors: 12,
      rentablePerFloor: 75,
      parkingSpots: 36,
      elevatorCount: 4,
      coreSizeM2: 120,
      export: "IFC + GLB + leasing pack",
    },
  },
  "retail-flagship": {
    name: "retail-flagship",
    description: "Flagship retail space with sales floor, fitting rooms, stockroom, facade and storefront glazing.",
    values: {
      frontageM: 14,
      depthM: 25,
      salesFloorM2: 350,
      floors: 2,
      fittingRooms: 3,
      stockroomM2: 80,
      storefronts: 1,
      parkingSpots: 8,
      export: "GLB + render pack + plan",
    },
  },
  "hospitality-hotel": {
    name: "hospitality-hotel",
    description: "Boutique hotel model with guest rooms, lobby, restaurant, terrace, back-of-house and parking.",
    values: {
      lotAreaM2: 1200,
      floors: 4,
      rooms: 28,
      roomsPerFloor: 7,
      averageRoomM2: 32,
      lobbyM2: 95,
      restaurantM2: 110,
      terraceM2: 60,
      parkingSpots: 14,
      export: "GLB + IFC + brochure pack",
    },
  },
  "mixed-use-development": {
    name: "mixed-use-development",
    description: "Mixed-use podium with retail ground floor, office middle and residential top, plus parking and amenities.",
    values: {
      frontageM: 30,
      depthM: 50,
      totalAreaM2: 3200,
      retailAreaM2: 800,
      officeFloors: 6,
      officeAreaM2: 1200,
      residentialFloors: 8,
      residentialUnits: 24,
      residentialAreaM2: 960,
      parkingSpots: 38,
      podiumM2: 1500,
      export: "IFC + GLB + investor pack + leasing views",
    },
  },
  "medical-clinic": {
    name: "medical-clinic",
    description: "Outpatient medical clinic with waiting area, consultation rooms, imaging suite and pharmacy.",
    values: {
      frontageM: 10,
      depthM: 20,
      floorAreaM2: 200,
      floors: 2,
      consultationRooms: 4,
      imagingRooms: 1,
      waitingAreaM2: 60,
      pharmacyM2: 25,
      parkingSpots: 6,
      export: "GLB + IFC + compliance pack",
    },
  },
  "logistics-center": {
    name: "logistics-center",
    description: "Last-mile logistics hub with sorting area, loading docks, micro-warehouse and vehicle staging.",
    values: {
      frontageM: 18,
      depthM: 35,
      sortingAreaM2: 420,
      loadingDocks: 6,
      microWarehouseM2: 280,
      vehicleStagingM2: 150,
      floors: 1,
      parkingSpots: 10,
      export: "GLB + IFC + operations pack",
    },
  },
  "educational-campus": {
    name: "educational-campus",
    description: "Campus building prototype with classrooms, labs, library common area and outdoor courtyard.",
    values: {
      lotAreaM2: 4000,
      floors: 3,
      classrooms: 12,
      labs: 3,
      averageClassroomM2: 55,
      libraryM2: 180,
      commonAreaM2: 120,
      courtyardM2: 200,
      parkingSpots: 25,
      export: "GLB + IFC + campus plan",
    },
  },
  "senior-care-facility": {
    name: "senior-care-facility",
    description: "Senior living facility with private rooms, common areas, therapy wing and secure outdoor garden.",
    values: {
      lotAreaM2: 3500,
      floors: 2,
      rooms: 48,
      privateRooms: 36,
      sharedRooms: 12,
      commonAreaM2: 200,
      therapyWingM2: 120,
      gardenM2: 300,
      parkingSpots: 30,
      export: "IFC + GLB + care-plan pack",
    },
  },
  "coworking-space": {
    name: "coworking-space",
    description: "Flexible coworking hub with open desks, private offices, meeting rooms, event space and café.",
    values: {
      frontageM: 16,
      depthM: 30,
      openDesks: 64,
      privateOffices: 8,
      meetingRooms: 4,
      eventSpaceM2: 90,
      cafeM2: 45,
      floors: 1,
      parkingSpots: 10,
      export: "GLB + render pack + layout plan",
    },
  },
  "industrial-plant": {
    name: "industrial-plant",
    description: "Light manufacturing plant with production floor, mezzanine, utilities bay, loading and staff facilities.",
    values: {
      frontageM: 40,
      depthM: 60,
      productionFloorM2: 2400,
      mezzanineM2: 500,
      utilitiesBayM2: 180,
      loadingBayCount: 5,
      staffFacilitiesM2: 200,
      parkingSpots: 18,
      export: "IFC + GLB + process layout",
    },
  },
};

export function getParametricFeature(name: string): ParametricFeature | undefined {
  return parametricLibrary[name];
}
