import { AppShell } from "../../../src/ui/app-shell";
import { AgentActivityPanel } from "../../../src/ui/agent-activity-panel";
import { AgentSwarmPanel } from "../../../src/ui/agent-swarm-panel";
import { ProjectWorkbench } from "../../../src/ui/project-workbench";
import { ReferenceBenchmarkPanel } from "../../../src/ui/reference-benchmark-panel";
import { getProjectById } from "../../../src/server/mock-data";

type ProjectPageProps = {
  params: {
    projectId: string;
  };
};

export default function ProjectDetailPage({ params }: ProjectPageProps) {
  const project = getProjectById(params.projectId);

  if (!project) {
    return (
      <AppShell
        title="Project not found"
        eyebrow="Missing project"
        subtitle="The requested project id does not match any registered workspace."
      >
        <section className="panel panel--hero">
          <p className="section-label">404</p>
          <h2>No project data is available for this route.</h2>
        </section>
      </AppShell>
    );
  }

  return (
    <AppShell
      title={project.name}
      eyebrow={project.category}
      subtitle={project.summary}
    >
      <div className="cockpit-nav panel">
        <div className="cockpit-nav__copy">
          <p className="section-label">Cockpit navigation</p>
          <p className="section-subtitle">Segmented views for preview, analysis, and versions.</p>
          <div className="cockpit-nav__signals">
            <span className="cockpit-nav__signal">{project.status}</span>
            <span className="cockpit-nav__signal">{project.confidence} confidence</span>
            <span className="cockpit-nav__signal">{project.validationState}</span>
          </div>
        </div>
        <nav className="cockpit-tabs" aria-label="Project cockpit views">
          <a className="cockpit-tab cockpit-tab--active" href="#project-preview" aria-current="page">
            3D Preview
          </a>
          <a className="cockpit-tab" href="#project-analysis">
            Analysis
          </a>
          <a className="cockpit-tab" href="#project-swarm">
            Swarm
          </a>
          <a className="cockpit-tab" href="#project-scenarios">
            Scenarios
          </a>
          <a className="cockpit-tab" href="#project-versions">
            Versions
          </a>
        </nav>
      </div>
      <div className="project-layout">
        <section className="panel panel--hero panel--detail" id="project-analysis">
          <div className="panel__header">
            <div>
              <p className="section-label">Project detail</p>
              <h2>{project.name}</h2>
              <p className="section-subtitle">Category {project.category} · {project.dimensions}</p>
            </div>
            <div className="status-pill">{project.status}</div>
          </div>
          <div className="project-meta">
            <div>
              <span>Owner</span>
              <strong>{project.owner}</strong>
            </div>
            <div>
              <span>Target format</span>
              <strong>{project.exportTarget}</strong>
            </div>
            <div>
              <span>Last revision</span>
              <strong>{project.lastRevision}</strong>
            </div>
            <div>
              <span>Model confidence</span>
              <strong>{project.confidence}</strong>
            </div>
            <div>
              <span>Validation state</span>
              <strong>{project.validationState}</strong>
            </div>
            <div>
              <span>Generated by</span>
              <strong>{project.generatedBy}</strong>
            </div>
            <div>
              <span>Next action</span>
              <strong>{project.nextAction}</strong>
            </div>
            <div>
              <span>Compliance</span>
              <strong>{project.compliance.status}</strong>
            </div>
            <div>
              <span>Policy</span>
              <strong>{project.compliance.policy}</strong>
            </div>
          </div>
          <div className="metric-row metric-row--compact">
            {project.kpis.map((kpi) => (
              <div className="metric-card" key={kpi.label}>
                <span>{kpi.label}</span>
                <strong>{kpi.value}</strong>
                <small>{kpi.delta}</small>
              </div>
            ))}
          </div>
          <div className="metric-row metric-row--compact">
            {project.liveSignals.map((signal) => (
              <div className="metric-card" key={signal.label}>
                <span>{signal.label}</span>
                <strong>{signal.value}</strong>
                <small>
                  {signal.trend} · {signal.detail}
                </small>
              </div>
            ))}
          </div>
          <div id="project-swarm">
            <AgentSwarmPanel
              items={project.agentSwarm}
              title="Project-specific realtime swarm"
              subtitle="Fourteen specialist lanes stay mapped to geometry, validation, commercial framing, and release gates for this workspace."
            />
          </div>
          <ReferenceBenchmarkPanel
            references={project.referenceBenchmarks}
            commandItems={project.missionQueue}
            title="Reference-driven feature pressure"
          />
          <article className="engineering-panel" id="project-scenarios">
            <div className="panel__header">
              <div>
                <p className="section-label">Scenario board</p>
                <h3>What the next surreal wave would change</h3>
                <p className="section-subtitle">Live what-if comparisons that keep the product commercial, not just visually impressive.</p>
              </div>
              <div className="status-pill status-pill--soft">Decision theater</div>
            </div>
            <div className="comparison-grid">
              {project.scenarioBoard.map((scenario) => (
                <article className="comparison-card" key={scenario.name}>
                  <span>{scenario.status}</span>
                  <strong>{scenario.name}</strong>
                  <p>{scenario.detail}</p>
                  <div className="comparison-summary comparison-summary--compact">
                    <div className="comparison-summary__chip">
                      <span>Delta</span>
                      <strong>{scenario.delta}</strong>
                    </div>
                    <div className="comparison-summary__chip">
                      <span>Outcome</span>
                      <strong>{scenario.outcome}</strong>
                    </div>
                  </div>
                </article>
              ))}
            </div>
          </article>
          <div className="engineering-grid">
            <article className="engineering-panel">
              <p className="section-label">Engineering summary</p>
              <div className="engineering-grid__cols">
                <div><span>Mass</span><strong>{project.engineering.mass}</strong></div>
                <div><span>Volume</span><strong>{project.engineering.volume}</strong></div>
                <div><span>Stress</span><strong>{project.engineering.stress}</strong></div>
                <div><span>Factor of safety</span><strong>{project.engineering.fos}</strong></div>
                <div><span>Deflection</span><strong>{project.engineering.deflection}</strong></div>
                <div><span>Tolerance</span><strong>{project.engineering.tolerance}</strong></div>
                <div><span>Cost estimate</span><strong>{project.engineering.costEstimate}</strong></div>
                <div><span>Print time</span><strong>{project.engineering.printTime}</strong></div>
              </div>
            </article>
            <article className="engineering-panel" id="validation">
              <p className="section-label">Validation risks</p>
              <div className="risk-list">
                {project.risks.map((risk) => (
                  <div className="risk-item" key={risk.label}>
                    <div>
                      <strong>{risk.label}</strong>
                      <p>{risk.detail}</p>
                    </div>
                    <span>{risk.severity}</span>
                  </div>
                ))}
              </div>
            </article>
          </div>
          <article className="engineering-panel export-readiness" id="export-readiness">
            <div className="panel__header">
              <div>
                <p className="section-label">Export readiness</p>
                <h3>{project.exportTarget} package check</h3>
                <p className="section-subtitle">Pass and warn states for the current release gate.</p>
              </div>
              <div className="status-pill status-pill--soft">Pre-export review</div>
            </div>
            <div className="export-readiness__grid">
              <div className="export-readiness__item export-readiness__item--pass">
                <span>Export schema</span>
                <strong>Pass</strong>
                <p>{project.validationChecks.find((check) => check.name === "Export schema")?.result ?? project.exportTarget}</p>
              </div>
              <div className="export-readiness__item export-readiness__item--warn">
                <span>Tolerance stack</span>
                <strong>Warn</strong>
                <p>{project.engineering.tolerance} still needs one final clearance pass before release.</p>
              </div>
              <div className="export-readiness__item export-readiness__item--pass">
                <span>Revision lock</span>
                <strong>Pass</strong>
                <p>{project.lastRevision} is stable enough for a staged export handoff.</p>
              </div>
            </div>
            <div className="export-readiness__decision">
              <span>Decision summary</span>
              <strong>Ready for staging export, but keep the tolerance warning open until the next verification pass.</strong>
            </div>
          </article>
          <article className="engineering-panel export-readiness export-readiness--formats">
            <div className="panel__header">
              <div>
                <p className="section-label">Format readiness</p>
                <h3>Delivery readiness by file type</h3>
                <p className="section-subtitle">This is the part clients remember: what the system can export with confidence now.</p>
              </div>
              <div className="status-pill status-pill--soft">Client facing</div>
            </div>
            <div className="export-format-grid">
              {project.exportReadiness.map((item) => (
                <article className={`export-format-card export-format-card--${item.status}`} key={item.format}>
                  <div className="export-format-card__top">
                    <strong>{item.format}</strong>
                    <span>{item.priority}</span>
                  </div>
                  <div className="export-format-card__status">{item.status}</div>
                  <p>{item.note}</p>
                </article>
              ))}
            </div>
          </article>
          <div className="engineering-grid">
            <article className="engineering-panel">
              <p className="section-label">Feature stack</p>
              <div className="feature-list">
                {project.features.map((feature) => (
                  <div className="feature-list__item" key={feature.name}>
                    <strong>{feature.name}</strong>
                    <span>{feature.status}</span>
                    <p>{feature.detail}</p>
                  </div>
                ))}
              </div>
            </article>
            <article className="engineering-panel">
              <p className="section-label">Validation checks</p>
              <div className="feature-list">
                {project.validationChecks.map((check) => (
                  <div className="feature-list__item" key={check.name}>
                    <strong>{check.name}</strong>
                    <span>{check.status}</span>
                    <p>{check.result}</p>
                  </div>
                ))}
              </div>
            </article>
          </div>
          <div className="engineering-panel">
            <p className="section-label">Revision timeline</p>
            <div className="revision-timeline">
              {project.revisions.map((revision) => (
                <article className="revision-item" key={revision.version}>
                  <div className="revision-item__meta">
                    <strong>{revision.version}</strong>
                    <span>{revision.state}</span>
                  </div>
                  <p>{revision.change}</p>
                  <small>{revision.impact}</small>
                </article>
              ))}
            </div>
          </div>
          <div className="engineering-panel">
            <p className="section-label">Governed versions</p>
            <div className="revision-timeline">
              {project.versions.map((version) => (
                <article className="revision-item" key={version.id}>
                  <div className="revision-item__meta">
                    <strong>{version.label}</strong>
                    <span>{version.author}</span>
                  </div>
                  <p>{version.summary}</p>
                  <small>{version.createdAt}</small>
                </article>
              ))}
            </div>
          </div>
          <div className="engineering-panel">
            <p className="section-label">Compliance findings</p>
            <div className="risk-list">
              {project.compliance.findings.map((finding) => (
                <div className="risk-item" key={finding.code}>
                  <div>
                    <strong>{finding.code}</strong>
                    <p>{finding.message}</p>
                  </div>
                  <span>{finding.severity}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="tag-row">
            {project.tags.map((tag) => (
              <span className="tag-pill" key={tag}>
                {tag}
              </span>
            ))}
          </div>
          <div className="detail-callout">
            <div>
              <p className="section-label">Decision gate</p>
              <strong>Model is ready for another iteration before export approval.</strong>
            </div>
            <p>
              The next pass should reduce mass, preserve stress safety, and keep the part manufacturable in the
              current constraint envelope.
            </p>
          </div>
          <div className="revision-compare" id="project-versions">
            <div className="panel__header">
              <div>
                <p className="section-label">Revision comparison</p>
                <h3>{project.comparison.current} vs {project.comparison.baseline}</h3>
              </div>
            </div>
            <div className="comparison-summary">
              <div className="comparison-summary__chip">
                <span>Current</span>
                <strong>{project.comparison.current}</strong>
              </div>
              <div className="comparison-summary__chip">
                <span>Baseline</span>
                <strong>{project.comparison.baseline}</strong>
              </div>
              <div className="comparison-summary__chip">
                <span>Delta focus</span>
                <strong>Mass, stiffness, cost</strong>
              </div>
            </div>
            <div className="comparison-table">
              {project.comparison.deltas.map((delta) => (
                <article className="comparison-row" key={delta.label}>
                  <div>
                    <strong>{delta.label}</strong>
                    <span>
                      {delta.before} → {delta.after}
                    </span>
                  </div>
                  <div className="comparison-row__delta">
                    <span>{delta.change}</span>
                    <div className="comparison-bar">
                      <div className={`comparison-bar__fill ${delta.change.startsWith("-") ? "comparison-bar__fill--positive" : "comparison-bar__fill--neutral"}`} />
                    </div>
                  </div>
                </article>
              ))}
            </div>
          </div>
          <article className="engineering-panel">
            <div className="panel__header">
              <div>
                <p className="section-label">Scenario board</p>
                <h3>What the active swarm is testing now</h3>
              </div>
              <div className="status-pill status-pill--soft">Live comparison</div>
            </div>
            <div className="comparison-grid">
              {project.scenarioBoard.map((scenario) => (
                <article className="comparison-card" key={scenario.name}>
                  <span>{scenario.status}</span>
                  <strong>{scenario.name}</strong>
                  <p>{scenario.delta}</p>
                  <p>{scenario.outcome}</p>
                  <small>{scenario.detail}</small>
                </article>
              ))}
            </div>
          </article>
        </section>

        <ProjectWorkbench project={project} id="project-preview" />
        <AgentActivityPanel items={project.activity} />
      </div>
    </AppShell>
  );
}
